### ISSUE TITLE
Github actions CI currently fails to setup the package

### ISSUE THREAD

**Issue by tlfobe** [shirtsgroup/terphenyl_simulations#34]
With the current GH action workflow all PRs currently fail due to the `.github/workflow/python-package.yml` file not being correctly setup. I spent some time in #33 trying to get a few test cases setup to work. The tests I setup pass locally, however when setup remotely with GH actions the workflow fails.

There are some version issues in my environment file, as only Python 3.12 gets past setting up the environment. For the 3.12 python tests the CI check fails due to `rdkit` missing, despit `rdkit` being included in the `environment.yml` file.

**Comment by mattwthompson** [comment]
Your GHA YAML looks fine from a cursory check, your issues are probably because your conda environment YAMLs look like they're from running `conda env export` or something like that, which includes precise package pins. These environment exports are useful for documenting the environment you used in a particular study, but are unnecessarily strict and pretty much guarantees the solver won't find a solution. You probably want to remove the build & version constraints and you can probably also remove many dependencies that you don't directly import, resulting in a smaller environment file (i.e. https://github.com/openforcefield/openff-toolkit/blob/main/devtools/conda-envs/test_env.yaml). There's probably a way to get `env export` to work, haven't tried it myself: https://stackoverflow.com/a/55576493

Apologies if I'm glossing over details or if you're already aware of this - this is a fairly common issue (it's reasonable to assume that you can re-generated an environment from an environment export!) so I wanted to hop in in case that helps

**Comment by tlfobe** [comment]
Thanks for posting this! I just updated my environent.yml file to only include dependencies installed via `mamba install ...` to cut down on the strictness of the environment. All builds are now getting past the install, but I'm getting errors about not being able to import `rdkit`. I think this might be an issue where the environment python executable might not being used to run pytest

**Comment by mattwthompson** [comment]
That sounds plausible - sometimes I use `python -m pytest ...` instead of directly calling the `pytest` executable and it magically works. If not, you might want to poke around with stuff like `which python` / `python -c "import pytest"` etc

**Comment by tlfobe** [comment]
Adding `which python` and `conda info` shows that I don't have my environment activated...

```which python
  conda info

  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/shirtsgroup/terphenyl_simulations/actions/runs/8087838209/job/22100643235#step:5:3).9.18/x6[4](https://github.com/shirtsgroup/terphenyl_simulations/actions/runs/8087838209/job/22100643235#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.18/x64/lib
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
/opt/hostedtoolcache/Python/3.9.18/x64/bin/python

     active environment : None
       user config file : /home/runner/.condarc
 populated config files : /home/runner/work/_temp/setup-micromamba/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.[5](https://github.com/shirtsgroup/terphenyl_simulations/actions/runs/8087838209/job/22100643235#step:5:5).final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=[6](https://github.com/shirtsgroup/terphenyl_simulations/actions/runs/8087838209/job/22100643235#step:5:6).5.0=0
                          __unix=0=0
       base environment : /usr/share/miniconda  (writable)
      conda av data dir : /usr/share/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/share/miniconda/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/6.5.0-1015-azure ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 1001:12[7](https://github.com/shirtsgroup/terphenyl_simulations/actions/runs/8087838209/job/22100643235#step:5:7)
             netrc file : None
           offline mode : False```

**Comment by tlfobe** [comment]
I found the issue to be the shell not being properly intialized. I added:
```
defaults:
  run:
    shell: bash -l {0}

```
to the top of my GHA yml file and things seem to be working now. see #35

**Comment by mattwthompson** [comment]
Was just about to say - you found exactly the sharp edge I've cut myself on many times in the past!
